version: '3.8'

services:
  personalapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      # Conectar a SQL Server externo en producción
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER};Database=SIMACHDB;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;Encrypt=true;
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
